name: Module CI/CD

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Get the version from the tag
      - name: Extract tag version number
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Echo tag output
        run: echo ${{ steps.get_version.outputs.version-without-v }}

      # Substitute the Manifest and Download URLs in the module.json
      - name: Substitute Manifest and Download Links
        id: sub_manifest_link_version
        uses: microsoft/variable-substitution@v1
        with:
          files: './module.json'
        env:
          version: ${{ steps.get_version.outputs.version-without-v }}
          url: https://github.com/${{ github.repository }}
          manifest: https://github.com/${{ github.repository }}/releases/latest/download/module.json
          download: https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/module.zip

      # Zip everything for the release
      - name: Zip files
        run: zip -r ./module.zip module.json lang/ scripts/ styles/ templates/

      # Create a release for this specific version
      - name: Create Versioned Release
        id: create_version_release
        uses: ncipollo/release-action@v1.13.0
        with:
          allowUpdates: true
          name: Release ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './module.json,./module.zip'
          tag: ${{ steps.get_version.outputs.version }}

      # Optionally update the 'latest' tag if this came from main
      - name: Create 'Latest' Release
        id: create_latest_release
        if: endsWith(github.ref, 'main')
        uses: ncipollo/release-action@v1.13.0
        with:
          allowUpdates: true
          name: Latest
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './module.json,./module.zip'
          tag: latest
